<a href="https://colab.research.google.com/github/areebaarshadqureshi/Data-Science-Journey-CampusX/blob/main/07-Pandas/03-Series-and-DataFrame-Functions/Functions_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None

# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [ ]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
team=df['Team'].unique()
t2=df['Against'].unique()
team=np.append(team,t2)
team=np.unique(team)
team.size

33

In [ ]:
dic={}
def filter_func(team):
  t=df[(df['Against']==team)|(df['Team']==team)]
  t_attempts=t['Total Attempts'].sum()
  t_target=t['On Target'].sum()
  if t_attempts > 0:
    per=np.round((t_target/t_attempts)*100,2)
  else:
     per=0.0

  dic[team]=per

for t1 in team:
  filter_func(t1)

In [ ]:
s = dict(sorted(dic.items(), key=lambda x: x[1], reverse=True))
print(s)

{'Argentina': np.float64(42.86), 'Serbia': np.float64(42.68), 'Switzerland': np.float64(41.56), 'Cameroon': np.float64(41.43), 'Brazil': np.float64(41.13), 'Ecuador': np.float64(40.82), 'Ghana': np.float64(40.58), 'England': np.float64(38.46), 'Qatar': np.float64(38.0), 'Iran': np.float64(37.14), 'Croatia': np.float64(37.04), 'Netherlands': np.float64(37.04), 'Germany': np.float64(36.96), 'Portugal': np.float64(36.94), 'Saudi Arabia': np.float64(36.84), 'Costa Rica': np.float64(36.49), 'Spain': np.float64(36.49), 'Poland': np.float64(35.92), 'United States': np.float64(35.9), 'France': np.float64(35.54), 'Korea Republic': np.float64(35.05), 'Canada': np.float64(33.33), 'Senegal': np.float64(32.95), 'Tunisia': np.float64(32.2), 'Australia': np.float64(31.82), 'Mexico': np.float64(31.34), 'Wales': np.float64(30.88), 'Japan': np.float64(30.1), 'Belgium': np.float64(29.87), 'Uruguay': np.float64(29.51), 'Denmark': np.float64(28.57), 'Morocco': np.float64(25.19), 'Fram': np.float64(7.69)}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
Team_played=df['Team'].value_counts()+df['Against'].value_counts()
Team_played.rank(method='first').sort_values(ascending=True)

Belgium            1.0
Cameroon           2.0
Canada             3.0
Costa Rica         4.0
Denmark            5.0
Ecuador            6.0
Germany            7.0
Ghana              8.0
Iran               9.0
Mexico            10.0
Qatar             11.0
Saudi Arabia      12.0
Serbia            13.0
Tunisia           14.0
Uruguay           15.0
Wales             16.0
Australia         17.0
Japan             18.0
Korea Republic    19.0
Poland            20.0
Senegal           21.0
Spain             22.0
Switzerland       23.0
United States     24.0
Brazil            25.0
England           26.0
Netherlands       27.0
Portugal          28.0
France            29.0
Argentina         30.0
Croatia           31.0
Morocco           32.0
Fram               NaN
Name: count, dtype: float64

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

In [ ]:
df.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,13.562500,4.671875,4.906250,4.648438,12.234375,92.703125,12.453125,169.281250,109.476562,14.812500,8.265625,1.726562,0.023438,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,6.901729,2.886595,3.080131,2.936573,6.176517,29.440547,18.152399,34.120661,30.776298,7.230458,5.101311,1.514834,0.151883,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,32.000000,0.000000,56.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,8.000000,2.000000,3.000000,3.000000,8.000000,72.750000,7.000000,149.500000,87.750000,10.000000,5.000000,1.000000,0.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,12.000000,4.500000,4.000000,4.000000,11.000000,93.000000,9.000000,170.500000,106.000000,15.000000,8.000000,2.000000,0.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,18.000000,7.000000,6.250000,6.000000,16.250000,111.250000,14.000000,188.000000,129.000000,20.000000,11.000000,2.000000,0.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,36.000000,13.000000,16.000000,19.000000,29.000000,186.000000,192.000000,259.000000,192.000000,40.000000,27.000000,8.000000,1.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000

In [ ]:
df.isnull().sum()

Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.drop(columns=["Sl. No", "Match No.", "Red Cards","Pts"],inplace=True)

In [ ]:
df

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,15,3,453,387,10,5,1,19,0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,15,4,484,419,26,10,3,17,1
2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,9,2,810,733,29,9,8,16,0
3,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,14,2,232,156,11,3,0,10,1
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,13,2,391,326,22,8,6,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Morocco,Fram,F,0,55,0,0,0,13,1,6,8,5,10,4,6,6,19,74,15,141,95,18,11,1,11,3,583,518,22,1,3,15,0
124,Croatia,Morocco,F,2,45,2,0,2,14,4,8,7,7,20,8,3,2,7,106,15,164,114,23,12,0,13,2,491,430,21,3,6,13,0
125,Morocco,Croatia,F,1,45,1,0,0,7,2,5,5,2,13,1,3,7,16,75,10,150,97,14,8,2,11,2,494,428,20,5,3,15,0
126,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,26,4,648,544,20,4,6,22,5
127,France,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,19,4,516,419,24,3,5,28,4

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
df['Rank']=df['Team'].rank()

In [ ]:
df['Rank']=df['Rank'].astype(np.int64)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Team                             128 non-null    object
 1   Against                          128 non-null    object
 2   Group                            128 non-null    object
 3   Goal                             128 non-null    int64
 4   Possession (%)                   128 non-null    int64
 5   Inside Penalty Area              128 non-null    int64
 6   Outside Penalty Area             128 non-null    int64
 7   Assists                          128 non-null    int64
 8   Total Attempts                   128 non-null    int64
 9   On Target                        128 non-null    int64
 10  Off Target                       128 non-null    int64
 11  Target in Penalty                128 non-null    int64
 12  Target from Outside              128 non-null    int64
 13  Left Channel                     128 non-null    int64
 14  Left Inside Channel              128 non-null    int64
 15  Central Channel                  128 non-null    int64
 16  Right Inside Channel             128 non-null    int64
 17  Right Channel                    128 non-null    int64
 18  Receptions MD                    128 non-null    int64
 19  Receptions D                     128 non-null    int64
 20  Attempted Line Breaks            128 non-null    int64
 21  Completed Line Breaks            128 non-null    int64
 22  Attempted Defensive Line Breaks  128 non-null    int64
 23  Completed Defensive Line Breaks  128 non-null    int64
 24  Yellow Cards                     128 non-null    int64
 25  Fouls Against                    128 non-null    int64
 26  Offsides                         128 non-null    int64
 27  Passes                           128 non-null    int64
 28  Passes Completed                 128 non-null    int64
 29  Crosses                          128 non-null    int64
 30  Crosses Completed                128 non-null    int64
 31  Corners                          128 non-null    int64
 32  Free Kicks                       128 non-null    int64
 33  Penalties Scored                 128 non-null    int64
 34  Rank                             128 non-null    int64
dtypes: int64(32), object(3)
memory usage: 35.1+ KB

In [ ]:
df.set_index('Rank',inplace=True)

In [ ]:
df.sort_index(inplace=True)
df

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,6,10,4,12,4,5,8,18,91,27,195,127,10,8,0,7,10,593,525,36,15,9,21,1
4,Argentina,Mexico,C,2,50,1,1,2,5,2,3,2,3,10,6,2,4,12,89,2,150,100,10,5,1,15,2,533,464,14,2,4,23,0
4,Argentina,Croatia,C,3,34,3,0,1,10,7,2,7,3,8,9,7,3,2,121,7,147,91,17,7,2,15,1,408,344,8,2,2,6,1
4,Argentina,Netherlands,C,2,44,2,0,1,15,6,8,5,10,7,7,13,6,17,104,7,203,122,24,8,8,18,2,603,511,16,4,8,30,5
4,Argentina,Australia,C,2,53,2,0,1,14,5,7,11,3,15,6,11,2,17,127,8,181,135,16,8,0,8,4,711,635,6,1,1,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,Uruguay,Portugal,H,0,35,0,0,0,10,3,6,6,4,13,8,4,5,9,94,6,150,86,17,11,2,16,0,390,306,18,5,2,13,0
124,Uruguay,Ghana,H,2,39,2,0,1,12,7,5,7,5,7,2,13,3,17,186,14,186,124,24,14,3,11,2,446,361,15,4,2,20,0
127,Wales,United States,B,1,39,1,0,0,7,3,3,5,2,7,2,5,2,7,73,9,174,103,17,8,2,10,1,409,321,15,6,3,15,1
127,Wales,Iran,B,0,51,0,0,0,10,3,4,5,5,18,3,8,11,13,101,13,208,129,17,8,1,9,2,508,413,20,5,2,12,0
127,Wales,England,B,0,33,0,0,0,7,1,3,1,6,7,1,2,0,4,46,1,104,55,4,1,2,16,1,325,261,4,1,1,10,0

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [ ]:
url1=' https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv'
df1 = pd.read_csv(url1)
df1.head()

NameError: name 'pd' is not defined

In [ ]:
url2=' https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv'
df2 = pd.read_csv(url2)
df2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df1.dropna(subset=['Age'],inplace=True)

In [ ]:
df1.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [ ]:
df2['Age']=df2['Age'].fillna(20)
df2

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,20.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,20.0,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,20.0,1,1,2668,22.3583,NaN,C

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

In [ ]:
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"
df = pd.read_csv(ipl_matches)
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
df.replace({'Delhi Capitals':'Delhi Daredevils','Punjab Kings':'Kings XI Punjab',
            'Rising Pune Supergiant':'Rising Pune Supergiants'},inplace=True)
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Kings XI Punjab,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Kings XI Punjab,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [ ]:
t=df['Team1'].value_counts()+df['Team2'].value_counts()
match=pd.DataFrame({
    'TeamName':t.index,
    'MatchesPlayed':t.values
})

match.head(2)

              TeamName  MatchesPlayed
0  Chennai Super Kings            208
1      Deccan Chargers             75

In [ ]:
w_team=df['WinningTeam'].value_counts()

In [ ]:
match['win_num']=match['TeamName'].map(df['WinningTeam'].value_counts())

In [ ]:
match['Win%']=round((match['win_num']/match['MatchesPlayed'])*100,2).astype(str)+"%"
match

                       TeamName  MatchesPlayed  win_num    Win%
0           Chennai Super Kings            208      121  58.17%
1               Deccan Chargers             75       29  38.67%
2              Delhi Daredevils            224      103  45.98%
3                 Gujarat Lions             30       13  43.33%
4                Gujarat Titans             16       12   75.0%
5               Kings XI Punjab            218      101  46.33%
6          Kochi Tuskers Kerala             14        6  42.86%
7         Kolkata Knight Riders            223      114  51.12%
8          Lucknow Super Giants             15        9   60.0%
9                Mumbai Indians            231      131  56.71%
10                Pune Warriors             46       12  26.09%
11             Rajasthan Royals            192       96   50.0%
12      Rising Pune Supergiants             30       15   50.0%
13  Royal Challengers Bangalore            226      109  48.23%
14          Sunrisers Hyderabad            152       75  49.34%

In [ ]:
dict={}
list2=df['Team1'].unique()
t1=df['Team1'].unique()
t2=df['Team2'].unique()
t1=np.append(t1,t2)
list1=np.unique(t1)
city=df['City'].unique()
for i in list1:
  for j in i.split():
        if j in city:
          dict[i]=j
          break


manual_fix = {
    'Kings XI Punjab': 'Chandigarh',
    'Rajasthan Royals': 'Jaipur',
    'Lucknow Super Giants': 'Lucknow',
    'Gujarat Titans': 'Ahmedabad',
    'Gujarat Lions': 'Rajkot',
     'Deccan Chargers': 'Hyderabad'
}

dict.update(manual_fix)

team_city_df = pd.DataFrame(list(dict.items()), columns=['Team', 'City'])
team_city_df.set_index('Team', inplace=True)
team_city_df

                                   City
Team
Chennai Super Kings             Chennai
Delhi Daredevils                  Delhi
Kochi Tuskers Kerala              Kochi
Kolkata Knight Riders           Kolkata
Mumbai Indians                   Mumbai
Pune Warriors                      Pune
Rising Pune Supergiants            Pune
Royal Challengers Bangalore   Bangalore
Sunrisers Hyderabad           Hyderabad
Kings XI Punjab              Chandigarh
Rajasthan Royals                 Jaipur
Lucknow Super Giants            Lucknow
Gujarat Titans                Ahmedabad
Gujarat Lions                    Rajkot
Deccan Chargers               Hyderabad

In [ ]:
df['HomeCity'] = df['Team1'].map(team_city_df['City'])
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,HomeCity
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,Jaipur
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,Bangalore
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,Bangalore
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,Jaipur
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Kings XI Punjab,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Kings XI Punjab,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,Hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,Kolkata
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,Mumbai
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,Delhi
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,Chandigarh
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,Bangalore

In [ ]:
match['City']=match['TeamName'].map(team_city_df['City'])
match

                       TeamName  MatchesPlayed  win_num    Win%        City
0           Chennai Super Kings            208      121  58.17%     Chennai
1               Deccan Chargers             75       29  38.67%   Hyderabad
2              Delhi Daredevils            224      103  45.98%       Delhi
3                 Gujarat Lions             30       13  43.33%      Rajkot
4                Gujarat Titans             16       12   75.0%   Ahmedabad
5               Kings XI Punjab            218      101  46.33%  Chandigarh
6          Kochi Tuskers Kerala             14        6  42.86%       Kochi
7         Kolkata Knight Riders            223      114  51.12%     Kolkata
8          Lucknow Super Giants             15        9   60.0%     Lucknow
9                Mumbai Indians            231      131  56.71%      Mumbai
10                Pune Warriors             46       12  26.09%        Pune
11             Rajasthan Royals            192       96   50.0%      Jaipur
12      Rising Pune Supergiants             30       15   50.0%        Pune
13  Royal Challengers Bangalore            226      109  48.23%   Bangalore
14          Sunrisers Hyderabad            152       75  49.34%   Hyderabad

In [ ]:
match.set_index('TeamName',inplace=True)
df['is_home']=df['City']==df['HomeCity']
home_matches=df[df['is_home']]
matches=home_matches['Team1'].value_counts()
home_win=home_matches[home_matches['Team1']==home_matches['WinningTeam']]['Team1'].value_counts()
match['HomeWin%']=round((home_win/matches)*100,2).astype(str)+"%"
match

,MatchesPlayed,win_num,Win%,City,HomeWin%
TeamName,,,,,
Chennai Super Kings,208,121,58.17%,Chennai,71.43%
Deccan Chargers,75,29,38.67%,Hyderabad,16.67%
Delhi Daredevils,224,103,45.98%,Delhi,43.08%
Gujarat Lions,30,13,43.33%,Rajkot,30.0%
Gujarat Titans,16,12,75.0%,Ahmedabad,NaN
Kings XI Punjab,218,101,46.33%,Chandigarh,50.0%
Kochi Tuskers Kerala,14,6,42.86%,Kochi,40.0%
Kolkata Knight Riders,223,114,51.12%,Kolkata,60.61%
Lucknow Super Giants,15,9,60.0%,Lucknow,NaN
Mumbai Indians,231,131,56.71%,Mumbai,63.89%
Pune Warriors,46,12,26.09%,Pune,25.0%
Rajasthan Royals,192,96,50.0%,Jaipur,67.5%
Rising Pune Supergiants,30,15,50.0%,Pune,45.45%
Royal Challengers Bangalore,226,109,48.23%,Bangalore,46.67%
Sunrisers Hyderabad,152,75,49.34%,Hyderabad,68.57%

In [ ]:
df['away_home']=df['City']!=df['HomeCity']
away_home=df[df['away_home']]
won_m=away_home[away_home['Team1']==away_home['WinningTeam']]['Team1'].value_counts()
matches=away_home['Team1'].value_counts()
match['away_wi%']=round((won_m/matches)*100,2).astype(str)+'%'
match

,MatchesPlayed,win_num,Win%,City,HomeWin%,away_wi%
TeamName,,,,,,
Chennai Super Kings,208,121,58.17%,Chennai,71.43%,48.39%
Deccan Chargers,75,29,38.67%,Hyderabad,16.67%,47.62%
Delhi Daredevils,224,103,45.98%,Delhi,43.08%,51.02%
Gujarat Lions,30,13,43.33%,Rajkot,30.0%,33.33%
Gujarat Titans,16,12,75.0%,Ahmedabad,NaN,57.14%
Kings XI Punjab,218,101,46.33%,Chandigarh,50.0%,41.38%
Kochi Tuskers Kerala,14,6,42.86%,Kochi,40.0%,50.0%
Kolkata Knight Riders,223,114,51.12%,Kolkata,60.61%,41.03%
Lucknow Super Giants,15,9,60.0%,Lucknow,NaN,87.5%
Mumbai Indians,231,131,56.71%,Mumbai,63.89%,47.5%
Pune Warriors,46,12,26.09%,Pune,25.0%,28.57%
Rajasthan Royals,192,96,50.0%,Jaipur,67.5%,44.9%
Rising Pune Supergiants,30,15,50.0%,Pune,45.45%,66.67%
Royal Challengers Bangalore,226,109,48.23%,Bangalore,46.67%,50.0%
Sunrisers Hyderabad,152,75,49.34%,Hyderabad,68.57%,35.29%

###`Q-7:` Venues with most "no result" matches.

In [ ]:
df[df['WinningTeam'].isnull()]['Venue'].value_counts()

Venue
M Chinnaswamy Stadium    2
M.Chinnaswamy Stadium    1
Feroz Shah Kotla         1
Name: count, dtype: int64

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
dic={}
t1=df[df['MatchNumber']=="Final"]['Team1Players']
t2=df[df['MatchNumber']=="Final"]['Team2Players']
combined_players = pd.concat([t1, t2])
for i in combined_players:
  for j in i.split(','):
     j=j.strip("[]'/?")
     if j not in dic:
       dic[j]=1

     else:
       dic[j]+=1

players_data=pd.Series(dic)
players_data.sort_values(ascending=False).head(1)

'MS Dhoni    10
dtype: int64

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
def point_table(season):
  seasons=df[df['Season']==season]
  total_match=(seasons['Team1'].value_counts()+seasons['Team2'].value_counts()).sort_values(ascending=False)
  won=seasons['WinningTeam'].value_counts().sort_values(ascending=False)
  n_result=seasons['WinningTeam'].isnull().sum()

  points=pd.DataFrame({
      'TeamName':total_match.index,
      'MatchesPlayed':total_match.values,
      'MatchesWon':won.values,
      'NoResult':n_result,
      'Points':won.values*2+n_result
  })
  points.set_index('TeamName',inplace=True)

  print(points)

point_table('2022')

                             MatchesPlayed  MatchesWon  NoResult  Points
TeamName
Rajasthan Royals                        17          12         0      24
Gujarat Titans                          16          10         0      20
Royal Challengers Bangalore             16           9         0      18
Lucknow Super Giants                    15           9         0      18
Delhi Daredevils                        14           7         0      14
Chennai Super Kings                     14           7         0      14
Kolkata Knight Riders                   14           6         0      12
Kings XI Punjab                         14           6         0      12
Mumbai Indians                          14           4         0       8
Sunrisers Hyderabad                     14           4         0       8

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
def point_table(season):
  seasons=df[df['Season']==season]
  total_match=(seasons['Team1'].value_counts()+seasons['Team2'].value_counts()).sort_values(ascending=False)
  won=seasons['WinningTeam'].value_counts().sort_values(ascending=False)
  n_result=seasons['WinningTeam'].isnull().sum()
  point_t=pd.DataFrame({
      'TeamName':total_match.index,
      'MatchesPlayed':total_match.values,
      'MatchesWon':won.values,
      'NoResult':n_result,
      'Points':won.values*2+n_result,
  })
  point_t['Rank']=point_t['Points'].rank(ascending=False,method='first')
  point_t['Rank'] =point_t['Rank'].replace({1:'Winner',2:'Runner',3:'Qualifier',4:'Elininater'})
  point_t.set_index('TeamName',inplace=True)
  print(point_t)

point_table('2022')

                             MatchesPlayed  MatchesWon  NoResult  Points  \
TeamName
Rajasthan Royals                        17          12         0      24
Gujarat Titans                          16          10         0      20
Royal Challengers Bangalore             16           9         0      18
Lucknow Super Giants                    15           9         0      18
Delhi Daredevils                        14           7         0      14
Chennai Super Kings                     14           7         0      14
Kolkata Knight Riders                   14           6         0      12
Kings XI Punjab                         14           6         0      12
Mumbai Indians                          14           4         0       8
Sunrisers Hyderabad                     14           4         0       8

                                   Rank
TeamName
Rajasthan Royals                 Winner
Gujarat Titans                   Runner
Royal Challengers Bangalore   Qualifier
Lucknow Super Giants         Elininater
Delhi Daredevils                    5.0
Chennai Super Kings                 6.0
Kolkata Knight Riders               7.0
Kings XI Punjab                     8.0
Mumbai Indians                      9.0
Sunrisers Hyderabad                10.0